### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Doutianbao** [Junyi-99/ChatGPT-API-Leakage#11]
大佬
这个程序会跑多久时间才停下来

我感觉已经跑了一白天了~~

**Comment by Doutianbao** [comment]
现在是不是没有可用的漏网之鱼啦。。。

**Comment by Doutianbao** [comment]
![image](https://github.com/user-attachments/assets/205991b7-9a70-4804-9a27-19297ad92ed3)

Poor man

**Comment by Junyi-99** [comment]
> ![image](https://private-user-images.githubusercontent.com/25342342/374899424-205991b7-9a70-4804-9a27-19297ad92ed3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NzI3NDEsIm5iZiI6MTcyODQ3MjQ0MSwicGF0aCI6Ii8yNTM0MjM0Mi8zNzQ4OTk0MjQtMjA1OTkxYjctOWE3MC00ODA0LTlhMjctMTkyOTdhZDkyZWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDExMTQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2MDE3MDU2MTc4ZDhkOTUyNjQzNmEwMzVmZjUxZWZiZjk2ZGUyNmY1NTYwMTE2NGM2YjAxM2FmZGExZjVmYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PEUoEvwo0hkR9NAUol7NC7JkwOHK-Le66bfeo5V_od8)
> 
> Poor man

There is a `yes` in your result, that's a usable api key.
