### ISSUE TITLE
ModuleNotFoundError: No module named 'rich'

### ISSUE THREAD

**Issue by onepeople158** [Junyi-99/ChatGPT-API-Leakage#13]
Hello Developer, when I run the main program, I get the error message "ModuleNotFoundError: No module named 'rich'". Could you please tell me the reason for this?
![屏幕截图 2024-12-06 172001](https://github.com/user-attachments/assets/4ae4dd5c-d5a4-4dc7-ba92-c2945e77bd39)

**Comment by onepeople158** [comment]
![屏幕截图 2024-12-06 211503](https://github.com/user-attachments/assets/57deecc2-2eb8-4d27-b34c-29f5f79897b6)
This situation

**Comment by onepeople158** [comment]
> Did you try installing rich with `pip install rich`
![屏幕截图 2024-12-06 211503](https://github.com/user-attachments/assets/68a81b91-bf2c-4725-b814-5a40e19e11ff)
This situation

**Comment by KarinaNi** [comment]
`pip install selenium`

**Comment by Junyi-99** [comment]
@KarinaNi Thank you for your help!

@onepeople158 Please follow [the installation instructions](https://github.com/Junyi-99/ChatGPT-API-Leakage#installation)
