### ISSUE TITLE
How to resume from a partial result?

### ISSUE THREAD

**Issue by mesbahulalam** [Junyi-99/ChatGPT-API-Leakage#4]
I ran the script successfully but along the lines, there was an error and the script halted. I would very much like to start from the point it stopped working instead of starting from 0 again. How can I do that?
The error for reference is:
`🔍 Searching ...:  35%|█████████████▉                          | 182/522 [12:07:04<1081:46:41, 11454.12s/it]Traceback (most recent call last):
  File "/home/red/ChatGPT-API/ChatGPT-API-Leakage/main.py", line 352, in <module>
    main(from_iter=args.from_iter, check_existed_keys_only=args.check_existed_keys_only)
  File "/home/red/ChatGPT-API/ChatGPT-API-Leakage/main.py", line 321, in main
    leakage.search(from_iter=from_iter)
  File "/home/red/ChatGPT-API/ChatGPT-API-Leakage/main.py", line 217, in search
    self._process_url(url)
  File "/home/red/ChatGPT-API/ChatGPT-API-Leakage/main.py", line 124, in _process_url
    self.driver.get(url)
  File "/home/red/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "/home/red/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/home/red/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 288.007
  (Session info: chrome=126.0.6478.61)
Stacktrace:
#0 0x5556c728f6aa <unknown>
#1 0x5556c6f720dc <unknown>
#2 0x5556c6f59456 <unknown>
#3 0x5556c6f59035 <unknown>
#4 0x5556c6f56f76 <unknown>
#5 0x5556c6f575ef <unknown>
#6 0x5556c6f67f17 <unknown>
#7 0x5556c6f7e46e <unknown>
#8 0x5556c6f83b6b <unknown>
#9 0x5556c6f57d3a <unknown>
#10 0x5556c6f7e2ee <unknown>
#11 0x5556c70008f6 <unknown>
#12 0x5556c6fe1613 <unknown>
#13 0x5556c6fb14f7 <unknown>
#14 0x5556c6fb1e4e <unknown>
#15 0x5556c725587b <unknown>
#16 0x5556c7259921 <unknown>
#17 0x5556c724136e <unknown>
#18 0x5556c725a482 <unknown>
#19 0x5556c7225ccf <unknown>
#20 0x5556c727f0a8 <unknown>
#21 0x5556c727f280 <unknown>
#22 0x5556c728e7dc <unknown>
#23 0x7f050a1d2ac3 <unknown>`

**Comment by Junyi-99** [comment]
Try this

`python3 main.py --from-iter 182`

**Comment by mesbahulalam** [comment]
Although at the moment it stopped, it was validating the keys and --from-iter makes it starts the crawling process to gather keys, thank you for the help. Most people don't even try to help like you did so instantly,
