### ISSUE TITLE
How to start scanning after login

### ISSUE THREAD

**Issue by Cloudyy222** [Junyi-99/ChatGPT-API-Leakage#6]
This might be dumb cause I'm new to this, but after running the code and logging in my github account, theoretically i pressed enter, but of course it just made a new line. And I can't write a new command because the old one's still running.
$ python3 main.py
\U0001f4c2 Opening database file github.db
\U0001f30d Opening Chrome ...
\U0001f917 No cookies found, please login to GitHub first
Press Enter after you logged in:
 and that's it.

**Comment by Junyi-99** [comment]
It should be redirected to check if you really logged in.

**Comment by malfestio** [comment]
Similar issue here but does throw some errors.

`📂 Opening database file github.db
🌍 Opening Chrome ...

DevTools listening on ws://127.0.0.1:58269/devtools/browser/2214ac13-99bf-4c2a-99af-09bf1321c450
🤗 No cookies found, please login to GitHub first
Press Enter after you logged in: [18596:23680:0727/142140.483:ERROR:ssl_client_socket_impl.cc(883)] handshake failed; returned -1, SSL error code 1, net_error -100
[18596:23680:0727/142140.490:ERROR:ssl_client_socket_impl.cc(883)] handshake failed; returned -1, SSL error code 1, net_error -100
Created TensorFlow Lite XNNPACK delegate for CPU.
Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors (tensor#58 is a dynamic-sized tensor).
[18596:23680:0727/142153.686:ERROR:ssl_client_socket_impl.cc(883)] handshake failed; returned -1, SSL error code 1, net_error -100
[18596:23680:0727/142205.668:ERROR:ssl_client_socket_impl.cc(883)] handshake failed; returned -1, SSL error code 1, net_error -107`

**Comment by Junyi-99** [comment]
@malfestio What's the Chrome version and the chrome driver version you used?

plese try this command to upgrade your driver.

```bash
pip install --upgrade selenium -U
```

**Comment by malfestio** [comment]
doing an upgrade results in the same ssl errors

`📂 Opening database file github.db
🌍 Opening Chrome ...

DevTools listening on ws://127.0.0.1:62079/devtools/browser/a04ab472-3790-4999-a60f-341a7097d79c
🍪 Cookies found, loading cookies
🤗 Redirecting ...
[19988:26516:0727/145701.508:ERROR:ssl_client_socket_impl.cc(883)] handshake failed; returned -1, SSL error code 1, net_error -100
[19988:26516:0727/145701.513:ERROR:ssl_client_socket_impl.cc(883)] handshake failed; returned -1, SSL error code 1, net_error -100
🔍 Searching ...:   0%|                                                                        | 0/522 [00:00<?, ?it/s]�  Progress found, do you want to continue from the last progress (41/522)? [yes] | no: Created TensorFlow Lite XNNPACK delegate for CPU.
[19988:26516:0727/145711.652:ERROR:ssl_client_socket_impl.cc(883)] handshake failed; returned -1, SSL error code 1, net_error -100`

**Comment by Junyi-99** [comment]
@malfestio This seems to be a problem with your environment. I can't reproduce it, so I can't help you solve it. Moreover, this issue is not related to this project. Because the project is written in Python, but the error is raised by C++. The project can be used on Windows, macOS, and Ubuntu.

You might want to try using a different computer.

**Comment by Cloudyy222** [comment]
> It should be redirected to check if you really logged in.
I installed the requirements (python3.12, gg chrome) and install the package by git bash. I upgraded pip to 24.2. Then cd the folder and run it on Git Bash and it didn't work.,

**Comment by altafjava** [comment]
📂 Opening database file github.db
🌍 Opening Chrome ...

DevTools listening on ws://127.0.0.1:59730/devtools/browser/dbcdd092-abbf-4246-9aea-68974b0685f9
🍪 Cookies found, loading cookies
🤗 Redirecting ...
🔍 Searching ...:   0%|                                                                                                           | 0/1046 [00:00<?, ?it/s] 🔍 Progress found, do you want to continue from the last progress (0/1046)? [yes] | no: no
Created TensorFlow Lite XNNPACK delegate for CPU.
Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors (tensor#58 is a dynamic-sized tensor).
🔍 Searching ...:   0%|                                                                                                | 1/1046 [00:46<13:37:50, 46.96s/it] 🔴 Error, unable to find the iframe, continue anyway
[]
🔴 Error, unable to find the iframe, continue anyway
[]
🔴 Error, unable to find the iframe, continue anyway
[]
🔴 Error, unable to find the iframe, continue anyway
[]
🔴 Error, unable to find the iframe, continue anyway
[]
🔴 Error, unable to find the iframe, continue anyway

**Comment by Junyi-99** [comment]
@altafjava Thanks for reporting this. Do you mind opening a separate issue? I have successfully reproduced this and am ready to fix it. Thank you for your help.

**Comment by Junyi-99** [comment]
Close as not relevant to this repo. 

Please check the installation and configuration of `selenium` and `chrome`
