### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by TriDev-Studios** [Junyi-99/ChatGPT-API-Leakage#7]
`Traceback (most recent call last):
  File "/home/runner/AI-Coder/ChatGPT-API-Leakage/main.py", line 17, in <module>
    from utils import (
  File "/home/runner/AI-Coder/ChatGPT-API-Leakage/utils.py", line 7, in <module>
    from openai import AuthenticationError, OpenAI, RateLimitError
ImportError: cannot import name 'AuthenticationError' from 'openai' (/home/runner/AI-Coder/.pythonlibs/lib/python3.11/site-packages/openai/__init__.py)`

**Comment by Junyi-99** [comment]
Which version of the `openai` package are you using?

**Comment by Junyi-99** [comment]
Closed for no-response
